openapi: 3.0.3
info:
  title: ai-interaction-api
  description: fetches data from openai source with user request
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: local development
    variables:
      port:
        default: "8080"
      basePath:
        default: "v1"

components:
  schemas:
    data:
      type: object
      properties:
        Urls:
          type: array
          items:
            format: string
    request:
      type: object
      properties:
        prompt:
          type: string
        size:
          type: string
        n:
          type: integer
          format: int64

paths:
  /image:
    parameters:
      - name: prompt
        in: query
        schema:
          type: string
    description: get images
    post:
      description: "get ai generated images"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/request"
      responses:
        200:
          description: "successful response with data"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/data"
        default:
          description: "default response"
          content:
            application/json:
              schema:
                type: string

  
