### API Test POST Image
POST https://api.openai.com/v1/images/generations
Content-Type: application/json
Authorization: {{api-key}}

< request.json
> handler.js

###

POST localhost:8080/v1/image
Content-Type: application/json
Authorization: {{api-key}}

< request.json
> handler.js

###
