### Send POST request with json body
POST https://api.openai.com/v1/images/generations
Content-Type: application/json
Authorization: {{api-key}}

{
  "prompt": "a cute cat playing guitar",
  "n": 2,
  "size": "1024x1024"
}
###

POST localhost:8080/image
Content-Type: application/json
Authorization: {{api-key}}

{
  "prompt": "a cute cat playing guitar",
  "n": 2,
  "size": "1024x1024"
}

